DROP TABLE obracuni;

CREATE TABLE obracuni (
	rb int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	partner integer NOT NULL,
	id VARCHAR(5) NOT NULL,
	jelo boolean NOT NULL,
	kolicina float NOT NULL,
	cijena float NOT NULL,
	vrijeme TIMESTAMP NOT NULL,
	FOREIGN KEY (partner) REFERENCES partneri (id)
);

GRANT SELECT, UPDATE, INSERT ON TABLE obracuni TO "aplikacija";

INSERT INTO obracuni (PARTNER,ID,JELO,KOLICINA,CIJENA,VRIJEME) VALUES
	 (1,'p1',false,2.0,3.0,now()),
	 (1,'MK1',true,1.0,12.0,now());


