name: tsmetisko_docker_compose

networks:
  mreza_tsmetisko:
    external: true
          
volumes:
   svezak_tsmetisko:
      external: true
      
services:
   tvrtka:
      image: tvrtka_tsmetisko
      container_name: tvrtka_tsmetisko
      build:
         context: ./tsmetisko_vjezba_08_dz_3_tvrtka
         dockerfile: Dockerfile
      volumes:
      -  type: volume
         source: svezak_tsmetisko
         target: /usr/app/podaci
         volume:
            nocopy: true
      networks:
        mreza_tsmetisko:
          ipv4_address: 20.24.5.2
          
   partner:
      image: partner_tsmetisko
      container_name: partner_tsmetisko
      build:
         context: ./tsmetisko_vjezba_08_dz_3_partner
         dockerfile: Dockerfile
      volumes:
      -  type: volume
         source: svezak_tsmetisko
         target: /usr/app/podaci
         volume:
            nocopy: true
      networks:
        mreza_tsmetisko:
          ipv4_address: 20.24.5.3
      depends_on:
      - tvrtka
      
   servisi:
      image: servis_tsmetisko
      container_name: servis_tsmetisko
      build:
         context: ./tsmetisko_vjezba_08_dz_3_servisi
         dockerfile: Dockerfile
      volumes:
      -  type: volume
         source: svezak_tsmetisko
         target: /usr/app/podaci
         volume:
            nocopy: true
      networks:
        mreza_tsmetisko:
          ipv4_address: 20.24.5.20
      depends_on:
      - partner
      
      
